#!/usr/bin/env bash
set -euo pipefail
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# When this script exits kill all its children
trap 'kill -- -$$ &>/dev/null' EXIT

"$SCRIPT_DIR/pbcopy/build"       "$@" &
"$SCRIPT_DIR/pbpaste/build"      "$@" &
"$SCRIPT_DIR/bringtofront/build" "$@" &

# Wait until all scripts are done
wait &>/dev/null
