#!/usr/bin/env bash
set -euo pipefail
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DEST="$HOME/bin"
mkdir -p "$DEST"

cp "$SCRIPT_DIR/pbcopy/bin/Release/pbcopy.exe" "$DEST"
cp "$SCRIPT_DIR/pbpaste/bin/Release/pbpaste.exe" "$DEST"
