#!/usr/bin/env bash
set -euo pipefail
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DST="${1:-}"
DST="${DST:-"$HOME/bin"}"
mkdir -p "$DST"

"$SCRIPT_DIR/build" -c Release

while read -rd '' SRC; do
    SRC_NAME="$(basename "$SRC")"
    SRC_DIR="$SRC/bin/Release/netcoreapp3.1"
    cp -f "$SRC_DIR/$SRC_NAME.exe" "$SRC_DIR/$SRC_NAME.dll" "$SRC_DIR/$SRC_NAME.runtimeconfig.json" "$DST"
done < <(find "$SCRIPT_DIR" -mindepth 1 -maxdepth 1 -type d ! -iname "*.*" -print0)

cp "./tnet/bin/Release/netcoreapp3.1/CommandLine.dll" "$DST"
