#!/usr/bin/env bash
set -euo pipefail
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DEST="$SCRIPT_DIR/output"
mkdir -p "$DEST"
"$SCRIPT_DIR/install"

zip -j9 "$DEST/pbutils.zip" "$DEST/"*
