#!/usr/bin/env bash
set -euo pipefail
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DST="$SCRIPT_DIR/.output"
rm -rf "$DST"
mkdir -p "$DST"

"$SCRIPT_DIR/install" "$DST"

zip -j9 "pbutils.zip" "$DST/"*

rm -rf "$DST"
